### ISSUE TITLE
No support for cylinder shape?

### ISSUE THREAD

**Issue by dbackeus** [sverweij/atom-graphviz-preview-plus#13]
Noticed that when doing `shape="cylinder"` I just get regular boxes instead. The cylinder shape is documented at: http://www.graphviz.org/doc/info/shapes.html

New to graphviz so not sure if this is expected or not. Support for cylinder seems to vary between generators I've found online as well.

**Comment by sverweij** [comment]
Seems to be a problem in graphviz 2.38.0 itself. Apparently it is fixed in version 2.39.x and up (source: [this issue](https://github.com/ellson/graphviz/issues/84) in the graphviz repo). The viz.js (= graphviz compiled to javascript) version graphviz-preview-plus is using is on 2.38.0.

I've tried it against the latest official version of graphviz dot for Ubuntu  ([2.38.x](http://www.graphviz.org/Download_linux_ubuntu.php)) and that indeed complains _cylinder_ is an unknown shape. Other shapes seem to work fine.

```sh
$ dot -V
dot - graphviz version 2.38.0 (20140413.2041)
$ dot -T svg bla.dot > bla.svg
Warning: using box for unknown shape cylinder
```

```dot
digraph G {
    F1 [shape="star"]
    F2 [shape="cylinder"] 
    F1 -> F2 [label="relation"]
}
```

**Next step for graphviz-preview-plus is to upgrade to a more recent version of viz.js.**     
I've been hesitant to do so because viz.js versions more recent than 1.3.0 have unsafe javascript code that atom/ electron refuse to execute. I know of an interesting workaround for it, but I've been waiting for viz.js' [own roadmap](https://github.com/mdaines/viz.js/issues/75)) because there were no serious problems with 2.38.x. Yet.

That changes with this issue, so I'll look into the _interesting workaround_ :-) 

**What can you do in the mean time?**    
If you have a more recent command line version of graphviz dot on your system, you can tell graphviz-preview-plus to use that. 

Settings => Packages => graphviz-preview-plus => Settings => tick the box next to _Use Graphviz Command Line_ - see below.

![image](https://cloud.githubusercontent.com/assets/4822597/25443367/ed9e78e0-2aa7-11e7-8e98-d0ecaa06e8ef.png)
Don't worry about the '*experimental*' warning b.t.w. I'll remove it in the next version because I've since tested that on Ubuntu, MS-Windows and OSX/ MacOS extensively and it works without a hitch.

**Comment by dbackeus** [comment]
Thanks for the amazingly detailed reply. 

`brew install graphviz` and then checking the command line option worked just fine!

**Comment by sverweij** [comment]
(auto-closed by a commit - the good thing is that that commit indeed fixes this issue => will deploy to atom.io soon)
