### ISSUE TITLE
Can't output *.png V1.51

### ISSUE THREAD

**Issue by ggyuy1** [sverweij/atom-graphviz-preview-plus#24]
For some reason my install of the package won't output some graphs via png...

I can get it to do *.svg but not png not sure why.

**Comment by sverweij** [comment]
hi @ggyuy1, thanks for reaching out.

- Does this happen for any graph or specific one? If it's a specific graph - could you share it? (There's limitations to the size a png can have due to the way atom-graphviz-preview-plus generates it).
- If it's for all graphs: can you share....
  - ... the version of atom and on which platform you're on (windows, Mac, linux) 
  - ... the version of atom-graphviz-preview-plus you're using 
  - ... and whether you set atom-graphviz-preview-plus to use the graphviz command line or not

**Comment by ggyuy1** [comment]
When I posted that was the first graph I made with the tool.

I've since made some test ones using tutorial *.dot examples those seem to work fine in terms of outputting the png.

I will need to refactor the graph I made since it is for class assignment that is still ongoing, I'll post once I get some time to do this.

However in the meantime I am able to get the png via graphviz gvedit program

**Comment by sverweij** [comment]
Thanks, that helps. My guess is the resulting image would've been too big for atom to chew. I've put some code in to deliver a nice message (instead of silently failing) for graphs that are too big, but your graph probably fell through the cracks - hence I'm very interested.

@ the error you got when ticking graphviz command line: I'll try to reproduce that when I have access to a windows machine.

**Comment by ggyuy1** [comment]
See the attached file for refactored version of what I was trying to output as PNG
[CFG.zip](https://github.com/sverweij/atom-graphviz-preview-plus/files/1444315/CFG.zip)

**Comment by sverweij** [comment]
Thanks, that helps a lot! The issue is not a too big picture. Something else is going on. a-g-p-p uses a `canvas` element to convert svg to png. `canvas` is picky in what it accepts as input. 

Apparently canvas (silently!) fails on the non-breaking space html entities (`&nbsp;`) graphviz puts in the svg (no clue why it does that - removing them yields the same picture). Removing the `&nbsp;`'s from the svg successfully transforms to png :-/

I first have to understand more on why canvas behaves (maybe specifically in atom?) as such before thinking of a solution (workaround? warning?)

**Comment by sverweij** [comment]
@ggyuy1 I found the root cause. TL;DR: fix on its way (although not today ...).

- `&nbsp;` entities _are not defined in svg_. So any svg with `&nbsp;` in them is technically invalid. Chrome and FireFox are quite forgiving and render them regardless. Apple's Safari is more picky and complains in no uncertain terms (_error on line 14 at column 122: Entity 'nbsp' not defined_). Apparently the same holds for svg's on canvas.
- The fix is obvious: either define the `nbsp` entity or replace all occurrences with its numerical variant (`&#160;`). GraphViz' svg renderer should actually do that - but until it does I'll implement a workaround in g-v-p-p.
- Dilemma: will GraphViz svg renderer also emit other (html) entities, like `&gt` `&lt`;,` &amp;`,  and should g-v-p-p anticipate this?

A short test with svg-preview (which uses the same code for png export) shows that defining the `nbsp` entity on top of the svg indeed solves the issue(I put `<!DOCTYPE svg [<!ENTITY nbsp "&#160;">]>` on top of the document).
